<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Topics extends Model
{
    use SoftDeletes;

    protected $table = 'topics';


    protected $fillable = [
        'id_subject',
        't_name',
        't_order',
        't_state',
        'created_by',
        'updated_by',
        'deleted_by',
    ];

    const NAME = [
        'Archivo',
        'Corrección de Estilo',
        'Estudios Literarios',
        'Filosofía',
        'Historia',
        'Humanidades',
        'Información y Documentación',
        'Lingüística',
        'Redacción de documentos',
        'Teología',
        'Antropología',
        'Cine / Cinematografía',
        'Comunicación',
        'Comunicación Audiovisual',
        'Geografía',
        'Geografía y Ordenación del Territorio',
        'Periodismo',
        'Psicología',
        'Sociología',
        'Trabajo Social',
        'Artes Escénicas',
        'Artes Plásticas',
        'Conservación Restauración de Bienes Culturales',
        'Danza',
        'Diseño',
        'Diseño de Interiores',
        'Diseño de Moda',
        'Diseño de Productos',
        'Diseño Digital y Multimedia',
        'Diseño gráfico',
        'Fotografía',
        'Historia del Arte',
        'Música',
        'Paisajismo',
        'Gastronomía y Artes Culinarias',
        'Hotelería',
        'Turismo',
        'Astronomía y Astrofísica',
        'Biología',
        'Bioquímica',
        'Biotecnología',
        'Ciencia e Ingeniería de Datos',
        'Ciencia y Tecnología de los Alimentos',
        'Ciencias Ambientales',
        'Ciencias del Mar',
        'Ciencias Experimentales',
        'Enología',
        'Estadística',
        'Cartas de control',
        'Estadística',
        'Estadística descriptiva',
        'Estadística inferencial',
        'Probabilidad',
        'Física',
        'Dinámica',
        'Electromagnetismo',
        'Física',
        'Mecánica',
        'Ondas',
        'Geología',
        'Abstracta',
        'Álgebra',
        'Álgebra Lineal',
        'Análisis Numérico',
        'Cálculo actuarial',
        'Cálculo diferencial',
        'Cálculo espacial',
        'Cálculo integral',
        'Cálculo vectorial',
        'Ecuaciones diferenciales',
        'Geometría',
        'Geometría',
        'Geometría Euclidiana',
        'Gestión de operaciones',
        'Integración numérica',
        'Lógica',
        'Matemáticas',
        'Programación lineal',
        'Topología',
        'Trigonometría',
        'Vectorial',
        'Nanociencia y Nanotecnología',
        'Química',
        'Inorgánica',
        'Orgánica',
        'Administración y Dirección de Empresas',
        'Estudio de mercados',
        'Evaluación de proyectos',
        'Gerencia de Valor',
        'Gestión de personas',
        'Gestión de procesos',
        'Recursos humanos',
        'Toma de decisiones',
        'Ventas',
        'Asistencia en Dirección',
        'Ciencias del Trabajo y Recursos Humanos',
        'Ciencias del Transporte y Logística',
        'Ciencias Políticas y de la Administración Pública',
        'Comercio',
        'Contabilidad y Finanzas',
        'Análisis Contable',
        'Auditoría',
        'Contabilidad y Finanzas',
        'Costos',
        'Matemáticas Financiera',
        'Mercado de opciones',
        'Presupuesto',
        'Tributaria',
        'Criminología',
        'Economía',
        'Macroeconomía',
        'Microeconomía',
        'Política económica',
        'Marketing',
        'Marketing',
        'Marketing globalizado',
        'Matemáticas Financiera',
        'Negocios internacionales',
        'Protocolo y Organización de Eventos',
        'Publicidad y Relaciones Públicas',
        'Relaciones Internacionales',
        'Seguridad y Control de Riesgos',
        'Ciencias Biomédicas',
        'Ciencias de la Actividad Física y del Deporte',
        'Enfermería',
        'Genética',
        'Farmacia',
        'Fisioterapia',
        'Logopedia',
        'Medicina',
        'Anatomía',
        'Fisiopatología',
        'Histología',
        'Inmunidad',
        'Medicina',
        'Radiología',
        'Nutrición Humana y Dietética',
        'Odontología',
        'Óptica y Optometría',
        'Podología',
        'Terapia Ocupacional',
        'Veterinaria',
        'Derecho',
        'Internacional',
        'Ambiental',
        'Civil',
        'Penal',
        'Política',
        'Derechos humanos',
        'Animación',
        'Arquitectura',
        'Arquitectura Técnica / Ingeniería de la Edificación',
        'Desarrollo de Aplicaciones Web',
        'Diseño y Desarrollo de videojuegos',
        'Grado Abierto en Ingeniería y Arquitectura',
        'Ingeniería Aeroespacial',
        'Ingeniería Agroambiental',
        'Ingeniería Alimentaria',
        'Ingeniería Ambiental',
        'Ingeniería Biomédica',
        'Ingeniería Civil',
        'Hidráulica',
        'Hormigon',
        'Ingeniería Civil',
        'Resistencia de materiales',
        'Suelos',
        'Vigas y esfuerzos',
        'Ingeniería de Caminos Canales y Puertos',
        'Ingeniería de la Automoción',
        'Ingeniería de la Energía',
        'Ingeniería de las Industrias Agrarias y Alimentarias',
        'Ingeniería de los Materiales',
        'Ingeniería de Minas',
        'Ingeniería de Sistemas Audiovisuales / Sonido e Imagen',
        'Ingeniería de Sistemas Biológicos',
        'Ingeniería de Sistemas',
        'Bases de Datos',
        'Algoritmos',
        'Ingeniería de Sistemas',
        'Programación',
        'Ingeniería de Tecnología y Diseño Textil',
        'Ingeniería de Telecomunicación(Teleco) y de Sistemas de Comunicación',
        'Ingeniería del Software',
        'Ingeniería Eléctrica y Electrónica',
        'Ingeniería en Diseño Industrial y Desarrollo de Producto',
        'Ingeniería en Informática',
        'Ingeniería en Organización Industrial',
        'Ingeniería en Tecnologías Industriales',
        'Ingeniería Física',
        'Ingeniería Forestal/Ingeniería del Medio Natural',
        'Ingeniería Geológica',
        'Ingeniería Geomática y Topografía',
        'Ingeniería Industrial',
        'Ingeniería Matemática',
        'Ingeniería Mecánica',
        'Ingeniería Mecatrónica',
        'Ingeniería Náutica y Transporte Marítimo',
        'Ingeniería Naval y Oceánica',
        'Ingeniería Química',
        'Ingeniería Robótica',
        'Ingeniería Telemática',
        'Piloto y Dirección de Operaciones Aéreas',
        'Termodinámica',
        'Educación Infantil',
        'Pedagogía',
        'Educación',
        'Idiomas',
        'Alemán',
        'Francés',
        'Inglés',
        'Italiano',
        'Mandarín',
        'Portugués',
        'Lenguas Modernas -Lenguas Clásicas-Filologías',
        'Traducción e Interpretación',
    ];

    const ACTIVO = 1;

    // relaciones
    public function subject() {
        return $this->belongsTo(Subjects::class, 'id_subject');
    }

    public function tutorTopics() {
        return $this->hasMany(TutorTopic::class, 'id_topic');
    }
}
